name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # ----------------------------------------------------
  # 1. BUILD PHASE (Dependencies and Assets)
  # ----------------------------------------------------
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, dom, bcmath, curl
          tools: composer

      - name: 3. Install Composer packages
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: 4. Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 5. Install npm packages
        run: npm ci
        working-directory: ./frontend 

      - name: 6. Build frontend Assets
        run: npm run build
        working-directory: ./frontend
        
      # Archive the built files (including vendor/ and public/build) for the next job
      - name: 7. Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package
          path: |
            ./*
            !./node_modules # Exclude local node_modules
            !./frontend/node_modules # Exclude frontend node_modules

  # ----------------------------------------------------
  # 2. DEPLOY PHASE (Requires successful build)
  # ----------------------------------------------------
  deploy:
    needs: build # This job runs only if 'build' succeeds
    runs-on: ubuntu-latest
    
    steps:
      # 1. Download the built files and vendor directory
      - name: 1. Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: deployment-package
          path: .

      # 2. Deploy Updated Files using Rsync (THE ROBUST FIX)
      - name: 2. Deploy Updated Files via Rsync
        # We use ssh-action for rsync functionality, which is highly reliable for updates.
        uses: appleboy/ssh-action@v0.1.10 
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: ${{ secrets.SFTP_PORT }}
          
          # Rsync parameters
          source: "./" # Transfer the entire downloaded artifact contents
          target: "~/public_html/laravel/" # To the application root on Hostinger
          sync: true # Activate rsync for robust incremental transfer (only copies changed files)

          # Commands run on the Hostinger server AFTER the file sync is complete
          script: |
            echo "--- Starting Post-Deployment Cleanup on Hostinger ---"            
            
            # 1. Navigate to the Laravel application root
            cd ~/public_html/laravel/
            
            # 2. CLEAR CACHES (Crucial for seeing PHP/config changes)
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            
            # 3. Verification command (Used to check the file's timestamp/size)
            echo "=== Final verification timestamp ==="
            ls -la ~/public_html/laravel/app/Http/Controllers/Controller.php

            echo "--- Deployment Complete! ---"
