name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # ----------------------------------------------------
  # 1. BUILD PHASE (Dependencies and Assets)
  # ----------------------------------------------------
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, dom, bcmath, curl
          tools: composer

      - name: 3. Install Composer packages
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: 4. Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 5. Install npm packages
        run: npm ci
        working-directory: ./frontend 

      - name: 6. Build frontend Assets
        run: npm run build
        working-directory: ./frontend
        
      # Archive the build artifacts for the next job
      - name: 7. Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package
          path: |
            ./*
            !./node_modules
            !./frontend/node_modules
            # NOTE: We keep vendor/ here because it was built in step 3.

  # ----------------------------------------------------
  # 2. DEPLOY PHASE (Requires successful build)
  # ----------------------------------------------------
  deploy:
    needs: build # This job runs only if 'build' succeeds
    runs-on: ubuntu-latest
    
    steps:
      # Download the built files and vendor directory
      - name: 1. Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: deployment-package
          path: .

      # 2. Deploy Updated Files via SCP (FIX: Use a more specific transfer method)
      - name: 2. Deploy Updated Files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_HOST }} 
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: ${{ secrets.SFTP_PORT }}

          # CRITICAL: We explicitly list the directories to ensure they are copied fully.
          # This should force the overwrite and update the files reliably.
          source: "{app,bootstrap,config,database,public,resources,routes,vendor,frontend}"
          target: "~/public_html/laravel/"
          overwrite: true

      # 3. Post-Deployment Commands (Cache Clearing)
      - name: 3. Run Post-Deployment Commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: ${{ secrets.SFTP_PORT }}
          
          script: |
            echo "--- Starting Post-Deployment Cleanup on Hostinger ---"            
            cd ~/public_html/laravel/
            
            # CLEAR CACHES (Essential)
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            
            # Verification command (The file MUST show a current timestamp now)
            echo "=== Final verification timestamp ==="
            ls -la ~/public_html/laravel/app/Http/Controllers/Controller.php

            echo "--- Deployment Complete! ---"
