name: Deploy Laravel + Frontend via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # 3️⃣ Install Composer dependencies
      - name: Install Composer packages
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      # 4️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 5️⃣ Install npm dependencies
      - name: Install npm packages
        run: npm ci
        working-directory: ./frontend

      # 6️⃣ Build frontend
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      # 7️⃣ Deploy frontend assets - FIXED
      - name: Deploy Frontend Assets
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: ${{ secrets.SFTP_PORT }}
          source: "frontend/dist/*"
          target: "public_html/laravel/public/"
          rm: false
          overwrite: true

      # 8️⃣ Deploy backend files - FIXED (using correct action)
      - name: Deploy Backend Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: ${{ secrets.SFTP_PORT }}
          source: |
            app/
            bootstrap/
            config/
            database/
            resources/
            routes/
            public/index.php
            artisan
            composer.json
            composer.lock
          target: "public_html/laravel/"
          rm: false
          overwrite: true

      # 9️⃣ Verify Deployment
      - name: Verify Files Were Updated
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: ${{ secrets.SFTP_PORT }}
          script: |
            echo "=== Checking public folder ==="
            ls -la ~/public_html/laravel/public/
            echo "=== Checking for assets folder ==="
            ls -la ~/public_html/laravel/public/assets/ || echo "No assets folder yet"
            echo "=== Deployment verification complete ==="
