name: Deploy Laravel + Frontend via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # 3️⃣ Install Composer dependencies
      - name: Install Composer packages
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      # 4️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 5️⃣ Install npm dependencies
      - name: Install npm packages
        run: npm ci
        working-directory: ./frontend

      # 6️⃣ Build frontend
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      # 7️⃣ Deploy frontend assets (UPDATE ONLY)
      - name: Deploy Frontend Assets via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: ${{ secrets.SFTP_PORT }}
          source: "frontend/dist/**"
          target: "public_html/laravel/public/"
          rm: false  # ← Important: DON'T remove existing files
          overwrite: true  # ← Only overwrite if files exist

      # 8️⃣ Deploy backend files (UPDATE ONLY)
      - name: Deploy Backend via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USER }}
          server: ${{ secrets.SFTP_HOST }}
          ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: ${{ secrets.SFTP_PORT }}
          local_path: './'
          remote_path: 'public_html/laravel/'
          delete_remote_files: false  # ← Critical: Don't delete anything
          sftp_args: '-o ConnectTimeout=5'

       # 9️⃣ Verify Deployment
      - name: Verify Files Were Updated
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: ${{ secrets.SFTP_PORT }}
          script: |
            echo "=== Checking updated files ==="
            find ~/public_html/laravel/public/assets/ -name "*.js" -o -name "*.css" | head -5
            echo "=== Deployment verification complete ==="
