name: Deploy Laravel + Frontend via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # 3️⃣ Install Composer dependencies
      - name: Install Composer packages
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      # 4️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 5️⃣ Install npm dependencies
      - name: Install npm packages
        run: npm ci
        working-directory: ./frontend

      # 6️⃣ Build frontend
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      # 7️⃣ Deploy frontend assets
      - name: Deploy Frontend Assets
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: ${{ secrets.SFTP_PORT }}
          source: "frontend/dist/"
          target: "public_html/laravel/public/"
          rm: false
          overwrite: true

      # 8️⃣ Deploy backend files (FIXED - specific files only, no exclude)
      - name: Deploy Backend Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: ${{ secrets.SFTP_PORT }}
          source: |
            app/
            bootstrap/
            config/
            database/
            resources/
            routes/
            public/
            artisan
            composer.json
            README.md
          target: "public_html/laravel/"
          rm: false
          overwrite: true

      # 9️⃣ Verify Specific File Update
      - name: Verify File Update
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: ${{ secrets.SFTP_PORT }}
          script: |
            echo "=== Checking if Controller.php was updated ==="
            head -10 ~/public_html/laravel/app/Http/Controllers/Controller.php
            echo "=== File modification time ==="
            ls -la ~/public_html/laravel/app/Http/Controllers/Controller.php
            echo "=== Checking file content for deployment comment ==="
            grep -n "DEPLOYMENT" ~/public_html/laravel/app/Http/Controllers/Controller.php || echo "No deployment comment found"

      # 🔟 Laravel Post-Deployment Setup
      - name: Laravel Post-Deployment Setup
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: ${{ secrets.SFTP_PORT }}
          script: |
            cd ~/public_html/laravel
            composer install --no-dev --optimize-autoloader
            php artisan config:clear
            php artisan config:cache
            php artisan route:clear
            php artisan route:cache
            php artisan view:clear
            php artisan view:cache
            chmod -R 755 storage
            chmod -R 755 bootstrap/cache
            echo "✅ Laravel deployment setup complete"
